### ISSUE TITLE
Allow hostname lookup

### ISSUE THREAD

**Issue by Rei-Tw** [silentbaws/XLMultiplayer#22]
Instead of typing IPs which is pretty annoying, XLMultiplayer should support hostnames and IP addresses when trying to connect.

**Comment by silentbaws** [comment]
Do you mean like the server browser?

**Comment by silentbaws** [comment]
nvm I know what you mean, like if you have a domain for the IP you can connect with the domain name right?

**Comment by silentbaws** [comment]
Added to next version of multiplayer
