### ISSUE TITLE
Installer doesn't recognize XLShredMenu

### ISSUE THREAD

**Issue by jparcill** [silentbaws/XLMultiplayer#23]
Using Linux and mono to run the exe.

When I direct the Installer to the Skater XL directory, it gives me an error saying that I still need to install XLShredMenu which is already installed by UMM.

Is it possible for me to do the installation manually?

Or point me to the installer code so that I can override this check?

Thanks!

**Comment by GorgeousDan** [comment]
I use wine on linux to run the Server.exe, perhaps it might work for the MPInstaller too?
Have you tried?

**Comment by silentbaws** [comment]
fuck didn't see this until now. Yeah you can install manually there's a XLMultiplayer.zip in the installer zip just drag that into UMM and then copy all the DLLs except XLMultiplayer.dll into the root directory of SkaterXL
