### ISSUE TITLE
"0 has been timed out for not responding for 15 seconds"

### ISSUE THREAD

**Issue by blixten** [silentbaws/XLMultiplayer#37]
Server is set up, both router and windows firewall have been opened on UDP and TPC port 7777. Both me and friends can connect, server sets the nick, but then we can't see each other, and a while later we are disconnected. The server console reports:

"0 has been timed out for not responding for 15 seconds"

Can't figure out what's wrong. Any suggestion where to look?

**Comment by silentbaws** [comment]
As far as I know this is caused by not opening port 7778. The players need to connect to both ports for the server to work correctly. After port-forwarding 7778 for UDP the issue should be resolved
